trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CondaEnvironment@0
  inputs:
    environmentName: 'tmbuild'
    packageSpecs: 'python=3.7'
- script: conda build folly
  displayName: 'Conda build folly'

