trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: sudo install -d -m 0777 /usr/envs
  displayName: Fix Conda permissions
- task: CondaEnvironment@0
  inputs:
    environmentName: 'tmbuild'
    packageSpecs: 'python=3.7'
- script: conda install conda-build
  displayName: Install dependencies with conda
- script: conda build .
  displayName: 'Conda build tmap'

