package:
  name: tmap
  version: 1.0.0

build:
  number: 0
  skip: True  # [py<35]

extra:
  - conda-forge

source:
  path: ..
  
requirements:
  build:
    - {{ compiler('cxx') }} #[not osx]
    - cmake
    - python
    - setuptools
    - pybind11
    - ogdf
  host:
    - vs2015_runtime # [win]
    - python
    - pip
    - ogdf
  run:
    - vs2015_runtime # [win]
    - python
    - ogdf

about:
  home: http://gdb.tools
  license: MIT
  # license_file: LICENSE
  summary: 'A Python package for visualizing large, high-dimensional data sets.'
  description: 'A Python package for visualizing large, high-dimensional data sets.'
  dev_url: https://github.com/reymondgroup/mstmap

extra:
    recipe-maintainers:
        - daenuprobst
