package:
  name: tmap
  version: 1.0.2

build:
  number: 0
  binary_relocation: False # [osx]
  skip: True  # [py<35]

extra:
  - conda-forge

source:
  path: ..
  
requirements:
  build:
    - {{ compiler('cxx') }}
    - llvm-openmp # [osx]
    - cmake
    - python {{ python }}
    - setuptools
    - pybind11
    - ogdf
  host:
    - vs2015_runtime # [win]
    - llvm-openmp # [osx]
    - python
    - pip
    - ogdf
  run:
    - vs2015_runtime # [win]
    - llvm-openmp # [osx]
    - python
    - ogdf

# test:
#   imports:
#     - tmap
#   requires:
#     - pytest

about:
  home: http://gdb.tools
  license: MIT
  # license_file: LICENSE
  summary: 'A Python package for visualizing large, high-dimensional data sets.'
  description: 'A Python package for visualizing large, high-dimensional data sets.'
  dev_url: https://github.com/reymondgroup/mstmap

extra:
    recipe-maintainers:
        - daenuprobst
