# name: Build on Ubuntu, Windows, and MacOS
# on: [push, pull_request]
# jobs:
#   - job: Ubuntu
#     pool:
#       vmImage: "ubuntu-latest"

#     steps:
#       - script: |
#           source ${CONDA}/etc/profile.d/conda.sh
#           sudo chown -R ${USER} ${CONDA}
#           conda config --set always_yes yes --set changeps1 no
#           conda update -q conda
#           conda create --name tmbuild
#           conda activate tmbuild
#           conda install -y conda-build
#         displayName: Setup Conda
#       - bash: cd tmap
#       - script: |
#           source ${CONDA}/etc/profile.d/conda.sh
#           conda activate tmbuild
#           conda build ogdf-conda
#         displayName: "Conda build ogdf"
#       - script: |
#           source ${CONDA}/etc/profile.d/conda.sh
#           conda activate tmbuild
#           conda build tmap
#         displayName: "Conda build tmap"
#       - task: CopyFiles@2
#         displayName: "Copy Files to: $(build.artifactStagingDirectory)"
#         inputs:
#           SourceFolder: "/usr/share/miniconda/envs/tmbuild/conda-bld/linux-64/"
#           Contents: "*.tar.bz2"
#           TargetFolder: "$(build.artifactStagingDirectory)"
#       - task: PublishBuildArtifacts@1
#         displayName: "Publish Artifact: LinuxPackages"

#   - job: Windows
#     pool:
#       vmImage: vs2017-win2016
#     steps:
#       - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
#         displayName: Setup build environment
#       - script: |
#           conda config --set always_yes yes --set changeps1 no
#           conda update -q conda
#           conda create --name tmbuild
#           conda activate tmbuild
#           conda install -y conda-build
#         displayName: Setup Conda
#       - bash: cd tmap
#       - script: |
#           conda activate tmbuild
#           conda build  ogdf-conda
#         displayName: "Conda build ogdf"
#       - script: |
#           conda activate tmbuild
#           conda build tmap
#         displayName: "Conda build tmap"
#       - task: CopyFiles@2
#         displayName: "Copy Files to: $(build.artifactStagingDirectory)"
#         inputs:
#           SourceFolder: 'C:\Miniconda\conda-bld\win-64\'
#           Contents: "*.tar.bz2"
#           TargetFolder: "$(build.artifactStagingDirectory)"
#       - task: PublishBuildArtifacts@1
#         displayName: "Publish Artifact: WindowsPackages"

#   - job: MacOS
#     pool:
#       vmImage: macos-10.13
#     variables:
#       target_platform: 10.13
#     steps:
#       - bash: |
#           wget https://github.com/phracker/MacOSX-SDKs/releases/download/10.13/MacOSX$(target_platform).sdk.tar.xz
#           sudo mkdir /opt
#           sudo install -d -m 0777 /opt
#           tar Jxvf MacOSX$(target_platform).sdk.tar.xz -C /opt
#         displayName: Install MacOSX $(target_platform) SDK
#       - script: |
#           echo "Removing homebrew from Azure to avoid conflicts."
#           curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
#           chmod +x ~/uninstall_homebrew
#           ~/uninstall_homebrew -fq
#           rm ~/uninstall_homebrew
#         displayName: Remove Homebrew
#       - script: |
#           source ${CONDA}/etc/profile.d/conda.sh
#           sudo chown -R ${USER} ${CONDA}
#           conda config --set always_yes yes --set changeps1 no
#           conda update -q conda
#           conda create --name tmbuild
#           conda activate tmbuild
#           conda install -y conda-build
#         displayName: Setup Conda
#       - bash: cd tmap
#       - script: |
#           source ${CONDA}/etc/profile.d/conda.sh
#           conda activate tmbuild
#           conda build ogdf-conda
#         displayName: "Conda build ogdf"
#       - script: |
#           source ${CONDA}/etc/profile.d/conda.sh
#           conda activate tmbuild
#           conda build tmap
#         displayName: "Conda build tmap"
#       - task: CopyFiles@2
#         displayName: "Copy Files to: $(build.artifactStagingDirectory)"
#         inputs:
#           SourceFolder: "/usr/local/miniconda/envs/tmbuild/conda-bld/osx-64/"
#           Contents: "*.tar.bz2"
#           TargetFolder: "$(build.artifactStagingDirectory)"
#       - task: PublishBuildArtifacts@1
#         displayName: "Publish Artifact: MacOSPackages"






name: Build on Ubuntu, Windows, and MacOS
on: [push, pull_request, workflow_dispatch]

jobs:
  # build_ubuntu:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: conda-incubator/setup-miniconda@v2
  #       with:
  #         auto-update-conda: true
  #     - name: Setup conda environment
  #       shell: bash -l {0}
  #       run: |
  #         conda config --set always_yes yes --set changeps1 no
  #         conda create --name tmbuild
  #         conda activate tmbuild
  #         conda install -y conda-build
  #     - name: Build OGDF
  #       shell: bash -l {0}
  #       run: |
  #         conda activate tmbuild
  #         conda build ogdf-conda
  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: ogdf-conda-package
  #         path: "/usr/share/miniconda/envs/tmbuild/conda-bld/"
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Setup conda environment
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda create --name tmbuild
          conda activate tmbuild
          conda install -y conda-build
      - name: Build OGDF
        run: |
          conda activate tmbuild
          conda build ogdf-conda      
      - uses: actions/upload-artifact@v2
        with:
          name: ogdf-conda-package-win
          path: "/usr/share/miniconda/envs/tmbuild/conda-bld/"

  # build_macos:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: conda-incubator/setup-miniconda@v2
  #       with:
  #         auto-update-conda: true
  #     - name: Install MacOSX 10.15 SDK
  #       shell: bash -l {0}
  #       run: |
  #         wget https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX10.15.sdk.tar.xz
  #         sudo install -d -m 0777 /opt
  #         tar Jxvf MacOSX10.15.sdk.tar.xz -C /opt
  #     - name: Setup conda environment
  #       shell: bash -l {0}
  #       run: |
  #         conda config --set always_yes yes --set changeps1 no
  #         conda create --name tmbuild
  #         conda activate tmbuild
  #         conda install -y conda-build
  #     - name: Build OGDF
  #       shell: bash -l {0}
  #       run: |
  #         conda activate tmbuild
  #         conda build ogdf-conda